import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { env } from './config/env.js';
import { errorMiddleware } from './middleware/error.middleware.js';
import productRoutes from './routes/product.routes.js';
import categoryRoutes from './routes/category.routes.js';
import orderRoutes from './routes/order.routes.js';
import authRoutes from './routes/auth.routes.js';
import wishlistRoutes from './routes/wishlist.routes.js';
import couponRoutes from './routes/coupon.routes.js';
import campaignRoutes from './routes/campaign.routes.js';
import reviewRoutes from './routes/review.routes.js';
import settingsRoutes from './routes/settings.routes.js';
import bannerRoutes from './routes/banner.routes.js';
import otpRoutes from './routes/otp.routes.js';
const app = express();
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors({ origin: env.frontendUrl, credentials:true }));
app.use(express.json({ limit:'5mb' }));
app.use(express.urlencoded({ extended:true }));
app.use(rateLimit({ windowMs: 15*60*1000, max: 200 }));
app.get('/health', (_req,res)=>res.json({ ok:true, time: new Date().toISOString() }));
app.get('/api', (_req,res)=>res.json({ name:'Budget Bazar API', version:'1.0' }));
app.use('/api/products', productRoutes);
app.use('/api/categories', categoryRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/wishlist', wishlistRoutes);
app.use('/api/coupons', couponRoutes);
app.use('/api/campaigns', campaignRoutes);
app.use('/api/reviews', reviewRoutes);
app.use('/api/settings', settingsRoutes);
app.use('/api/banners', bannerRoutes);
app.use('/api/otp', otpRoutes);
app.use(errorMiddleware);
export default app;
