import { Router } from 'express';
import { createOrder, listOrders, getOrder, updateOrderStatus, trackOrder, myOrders } from '../controllers/order.controller.js';
import { authMiddleware } from '../middleware/auth.middleware.js';
import { adminMiddleware } from '../middleware/admin.middleware.js';
import { validate } from '../middleware/validation.middleware.js';
import { createOrderSchema, trackOrderSchema } from '../validators/order.validator.js';
const r = Router();
r.post('/', authMiddleware, validate(createOrderSchema), createOrder);
r.post('/track', validate(trackOrderSchema), trackOrder);
r.get('/my', authMiddleware, myOrders);
r.get('/', authMiddleware, adminMiddleware, listOrders);
r.get('/:id', authMiddleware, getOrder);
r.put('/:id/status', authMiddleware, adminMiddleware, updateOrderStatus);
export default r;
